# Generated by Django 5.0.7 on 2024-12-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
