# Generated by Django 5.0.7 on 2024-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_songs_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(upload_to='songimages'),
        ),
    ]
