# Generated by Django 5.0.7 on 2024-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='bgColor',
            field=models.CharField(max_length=200),
        ),
    ]
