# Generated by Django 5.0.7 on 2024-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_album_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='album',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
